-keep class com.cofc.guard.** { *; }
-keep class org.bouncycastle.** { *; }
-keep class okhttp3.** { *; }
-keep class retrofit2.** { *; }
-keep class androidx.room.** { *; }
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable
-assumenosideeffects class android.util.Log { *; }
